### PR TITLE
Update Font Awesome to 4.6.3, fix build issue w/ SVGO, update doc

### PR DESCRIPTION
**Pull request by sebastienbarre**
Updating Font Awesome to 4.6.3.

As mentioned in fontello/fontello#434, a new version of SVGO was required, the build would fail otherwise while trying to parse `config.yml`. I also updated the documentation to guide whoever will sync this repo with Font Awesome next time.

The new glyph names in `config.yml` were (tediously) lifted from Font Awesome. I didn't fix the aliases for the older glyphs, this will have to be done in another PR.

### CODE REVIEW

**Comment by puzrin** [comment]
Could you remove autogenerated files from commit? Those make very difficult to chaeck your changes

**Comment by sebastienbarre** [comment]
I'm not sure how to partially revert a commit that way.
The "only" files that were modified are:
```
config.yml
DEVELOPMENT.md 
package.json
src/original/fontawesome-webfont.svg
```
and `src/svg/ajust.svg` which was deleted, because it was misspelled (should be `adjust.svg`)

**Comment by puzrin** [comment]
Also, FA svg seems to be buggy. As far as i remember, i did this:

1. Open TTF in FontForge
2. Save as SVG.

**Comment by puzrin** [comment]
Font Awesome font in SVG format. I thing you taken it as is.

**Comment by puzrin** [comment]
```
git reset HEAD~1 # undo last connit without file change
git commit config.yml DEVELOPMENT.md package.json src/original -m "YOUR TEXT"
git push -f # Force push to override previous commit
```

**Comment by sebastienbarre** [comment]
OK. I didn't want to do a force push on a repo I didn't create, but if you are OK with it, give me a sec.

**Comment by puzrin** [comment]
> OK. I didn't want to do a force push on a repo I didn't create, but if you are OK with it, give me a sec.

You force push to your own fork, not here. But content of PR will be updated.

**Comment by sebastienbarre** [comment]
Here you go. The Font Awesome SVG was copied straight from the Font Awesome repo to `src/original/fontawesome-webfont.svg`. The generated demo looks good to me.

**Comment by puzrin** [comment]
Question about `config.yml` why it's changed so much? I mean "888 deletion"

Can it be windows-style newlines?

**Comment by sebastienbarre** [comment]
I'm on a Mac. The new icons are found after:
```
  # --------------------------------------------------
  # 4.6.3
  # --------------------------------------------------
```
I removed some triple newlines, and all
```
  - 
    css: cc-amex
    code: 0xf1f3
    uid: 4e7a8235533632f4df7ba7a2c68cd39d
    search: [amex, card]
```
were converted to
```
  - css: cc-amex
    code: 0xf1f3
    uid: 4e7a8235533632f4df7ba7a2c68cd39d
    search: [amex, card]
```
for readability and consistency and to help parsing the config file to find the aliases in Font Awesome. It takes a long time to match the glyph names. 

Unfortunately old aliases have issues; people using Font Awesome use the documented names, but some of these names were changed to something else in Fontello. To find the new names there is no other choice but to look at the icons one by one in Fontello. I would like to fix the aliases at some point, or at least the search aliases with the original Font Awesome names.

**Comment by puzrin** [comment]
As far as i understand, this is not the end of changes. Let me know when i should start updating result in fontello.

**Comment by sebastienbarre** [comment]
Thanks, I appreciate the merging. Give me a second to describe a different change, and of course you'll decide how we can fix the issue.

**Comment by sebastienbarre** [comment]
OK, it seems I was mistaken, I can't reproduce the issue I had searching for Font Awesome icons in Fontello, sorry. So as far as I'm concerned, please feel free to update Fontello using my commit, it has all the news icons since 4.3.0, about 115 of them.

It's possible that my confusion comes from the Font Awesome icons that are renamed in Fontello. Out of curiosity, why is the [`times`](http://fontawesome.io/icon/times/) icon named `cancel` in Fontello, for example?

**Comment by puzrin** [comment]
Fontello has multiple fonts, and it looks logical to have similar names for similar glyphs. Also, FA appeared after fontello.

I think, placing FA names to aliaces could be acceptable tradeoff.

**Pull request merged**
