### PR TITLE
Fix adjust icon typo.

### PR DESCRIPTION
**Pull request by mareksuscak**

### CODE REVIEW

**Comment by puzrin** [comment]
@mareksuscak coule you cleanup the first commit? Remove everything except source file change.

Also, if you wish, you can replace fontforge with `svg2ttf`. I did it in other font repos.

**Comment by mareksuscak** [comment]
@puzrin Do you think this PR might be useful after merging `Makefile` fixes in a separate PR? To be honest I don't even remember where and why I needed this thing. From what I see the changeset it fixes the typo in adjust icon name.

**Comment by puzrin** [comment]
Not principal IMHO. I kept this open to remember that letter should be fixed in next update :)

**Comment by sebastienbarre** [comment]
I might fixed some spelling too. And add some aliases to the Font Awesome icons as well. The rationale here is for people like me who are already using Font Awesome, but want to use Fontello to create a smaller font file. Each icon in font awesome has a name, but that name was often missing in Fontello when I tried to create my custom font -- I couldn't find some Font Awesome icons I was already using from Fontello's search box, I had to look at each one of them individually. It took some time...

**Comment by sebastienbarre** [comment]
FYI the issue with the `ajust` icon was fixed in the PR I pushed, which was just merged by @puzrin

**Comment by puzrin** [comment]
Closing then.

**Pull request closed without merging**
